#cloudbuild.yaml
steps:
# Build the new docker image.
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/$_ENV/$REPO_NAME/$REPO_NAME:$COMMIT_SHA:latest', '.']

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['tag', 'workspace_app:latest', 'eu.gcr.io/$PROJECT_ID/$_ENV/$REPO_NAME/$REPO_NAME:$COMMIT_SHA']

- name: 'docker/compose:1.19.0'
  args: ['up', '-d']

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['tag', 'molecular:latest', 'eu.gcr.io/$PROJECT_ID/$_ENV/$REPO_NAME/$REPO_NAME:$COMMIT_SHA']
# Build the new docker image.
# - name: 'docker'
#   args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/$_ENV/$REPO_NAME:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'molecular-project-skeleton:latest', 'eu.gcr.io/$PROJECT_ID/$_ENV/$REPO_NAME:latest']
# Push the new image to the registry.
images: ['eu.gcr.io/$PROJECT_ID/$_ENV/$REPO_NAME:latest']
