name: Build

on:
  push:
    # branches: TODO: comment back in
    #   - master
  create:
    tags:
      - v*

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: molecular-skeleton-project
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REGION: europe-west3
      

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Set env
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=${GITHUB_SHA}" >> $GITHUB_ENV
          fi


     # Build and push docker image

      - name: Build
        run: |-
           if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
             docker build -t eu.gcr.io/$PROJECT_ID/prod/$SERVICE_NAME:$RELEASE_VERSION .
           else
             docker build -t eu.gcr.io/$PROJECT_ID/dev/$SERVICE_NAME:$RELEASE_VERSION .
           fi

    # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
      # Push image to Google Container Registry
      - name: Push
        run: |-
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
             docker push eu.gcr.io/$PROJECT_ID/prod/$SERVICE_NAME:$RELEASE_VERSION
          else
             docker eu.gcr.io/$PROJECT_ID/dev/$SERVICE_NAME:$RELEASE_VERSION
          fi